//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  configBurnStatus: ConfigBurnStatus;
  configBurnStatusConnection: ConfigBurnStatusConnection;
  configNavigation: ConfigNavigation;
  configNavigationConnection: ConfigNavigationConnection;
  configSite: ConfigSite;
  configSiteConnection: ConfigSiteConnection;
  configPersonnel: ConfigPersonnel;
  configPersonnelConnection: ConfigPersonnelConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigBurnStatusArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigBurnStatusConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigBurnStatusFilter>;
};


export type QueryConfigNavigationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigNavigationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigNavigationFilter>;
};


export type QueryConfigSiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigSiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigSiteFilter>;
};


export type QueryConfigPersonnelArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigPersonnelConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigPersonnelFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  configBurnStatus?: InputMaybe<ConfigBurnStatusFilter>;
  configNavigation?: InputMaybe<ConfigNavigationFilter>;
  configSite?: InputMaybe<ConfigSiteFilter>;
  configPersonnel?: InputMaybe<ConfigPersonnelFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = ConfigBurnStatus | ConfigNavigation | ConfigSite | ConfigPersonnel | Homepage | Page | Folder;

export type ConfigBurnStatus = Node & Document & {
  __typename?: 'ConfigBurnStatus';
  fire_status: Scalars['String']['output'];
  burn_season_start?: Maybe<Scalars['String']['output']>;
  burn_season_end?: Maybe<Scalars['String']['output']>;
  burn_ban_status: Scalars['String']['output'];
  commercial_burn_ban_status: Scalars['String']['output'];
  rec_campfire_status: Scalars['String']['output'];
  state_campfire_status: Scalars['String']['output'];
  np_campfire_status: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigBurnStatusFilter = {
  fire_status?: InputMaybe<StringFilter>;
  burn_season_start?: InputMaybe<DatetimeFilter>;
  burn_season_end?: InputMaybe<DatetimeFilter>;
  burn_ban_status?: InputMaybe<StringFilter>;
  commercial_burn_ban_status?: InputMaybe<StringFilter>;
  rec_campfire_status?: InputMaybe<StringFilter>;
  state_campfire_status?: InputMaybe<StringFilter>;
  np_campfire_status?: InputMaybe<StringFilter>;
};

export type ConfigBurnStatusConnectionEdges = {
  __typename?: 'ConfigBurnStatusConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ConfigBurnStatus>;
};

export type ConfigBurnStatusConnection = Connection & {
  __typename?: 'ConfigBurnStatusConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigBurnStatusConnectionEdges>>>;
};

export type ConfigNavigationItemsChildren = {
  __typename?: 'ConfigNavigationItemsChildren';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type ConfigNavigationItems = {
  __typename?: 'ConfigNavigationItems';
  label: Scalars['String']['output'];
  folder?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  children?: Maybe<Array<Maybe<ConfigNavigationItemsChildren>>>;
};

export type ConfigNavigation = Node & Document & {
  __typename?: 'ConfigNavigation';
  header_highlight_url?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<ConfigNavigationItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ConfigNavigationItemsChildrenFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type ConfigNavigationItemsFilter = {
  label?: InputMaybe<StringFilter>;
  folder?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  children?: InputMaybe<ConfigNavigationItemsChildrenFilter>;
};

export type ConfigNavigationFilter = {
  header_highlight_url?: InputMaybe<StringFilter>;
  items?: InputMaybe<ConfigNavigationItemsFilter>;
};

export type ConfigNavigationConnectionEdges = {
  __typename?: 'ConfigNavigationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ConfigNavigation>;
};

export type ConfigNavigationConnection = Connection & {
  __typename?: 'ConfigNavigationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigNavigationConnectionEdges>>>;
};

export type ConfigSiteAddress = {
  __typename?: 'ConfigSiteAddress';
  street?: Maybe<Scalars['String']['output']>;
  city?: Maybe<Scalars['String']['output']>;
  state?: Maybe<Scalars['String']['output']>;
  zip?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  map?: Maybe<Scalars['String']['output']>;
};

export type ConfigSite = Node & Document & {
  __typename?: 'ConfigSite';
  site_name: Scalars['String']['output'];
  formal_site_name?: Maybe<Scalars['String']['output']>;
  site_desc?: Maybe<Scalars['String']['output']>;
  prodUrl?: Maybe<Scalars['String']['output']>;
  cloudinarySiteId?: Maybe<Scalars['String']['output']>;
  cloudinaryRootUrl?: Maybe<Scalars['String']['output']>;
  enable_cloudinary_rewrites?: Maybe<Scalars['Boolean']['output']>;
  opengraph_image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<ConfigSiteAddress>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ConfigSiteAddressFilter = {
  street?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  state?: InputMaybe<StringFilter>;
  zip?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  map?: InputMaybe<StringFilter>;
};

export type ConfigSiteFilter = {
  site_name?: InputMaybe<StringFilter>;
  formal_site_name?: InputMaybe<StringFilter>;
  site_desc?: InputMaybe<StringFilter>;
  prodUrl?: InputMaybe<StringFilter>;
  cloudinarySiteId?: InputMaybe<StringFilter>;
  cloudinaryRootUrl?: InputMaybe<StringFilter>;
  enable_cloudinary_rewrites?: InputMaybe<BooleanFilter>;
  opengraph_image?: InputMaybe<StringFilter>;
  address?: InputMaybe<ConfigSiteAddressFilter>;
};

export type ConfigSiteConnectionEdges = {
  __typename?: 'ConfigSiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ConfigSite>;
};

export type ConfigSiteConnection = Connection & {
  __typename?: 'ConfigSiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigSiteConnectionEdges>>>;
};

export type ConfigPersonnelPersonnel = {
  __typename?: 'ConfigPersonnelPersonnel';
  first_name: Scalars['String']['output'];
  last_name: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  rank?: Maybe<Scalars['String']['output']>;
  staff_type: Scalars['String']['output'];
  roles?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  photo?: Maybe<Scalars['String']['output']>;
};

export type ConfigPersonnel = Node & Document & {
  __typename?: 'ConfigPersonnel';
  title: Scalars['String']['output'];
  personnel?: Maybe<Array<Maybe<ConfigPersonnelPersonnel>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigPersonnelPersonnelFilter = {
  first_name?: InputMaybe<StringFilter>;
  last_name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  rank?: InputMaybe<StringFilter>;
  staff_type?: InputMaybe<StringFilter>;
  roles?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ConfigPersonnelFilter = {
  title?: InputMaybe<StringFilter>;
  personnel?: InputMaybe<ConfigPersonnelPersonnelFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ConfigPersonnelConnectionEdges = {
  __typename?: 'ConfigPersonnelConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ConfigPersonnel>;
};

export type ConfigPersonnelConnection = Connection & {
  __typename?: 'ConfigPersonnelConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigPersonnelConnectionEdges>>>;
};

export type HomepageImage_Gallery = {
  __typename?: 'HomepageImage_gallery';
  image: Scalars['String']['output'];
  image_alt: Scalars['String']['output'];
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  title: Scalars['String']['output'];
  number_news_stories?: Maybe<Scalars['Float']['output']>;
  image_gallery?: Maybe<Array<Maybe<HomepageImage_Gallery>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type HomepageImage_GalleryFilter = {
  image?: InputMaybe<ImageFilter>;
  image_alt?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  title?: InputMaybe<StringFilter>;
  number_news_stories?: InputMaybe<NumberFilter>;
  image_gallery?: InputMaybe<HomepageImage_GalleryFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  nav_order?: Maybe<Scalars['Float']['output']>;
  nav_title?: Maybe<Scalars['String']['output']>;
  nav_hidden?: Maybe<Scalars['Boolean']['output']>;
  sidebar?: Maybe<Scalars['JSON']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageBodyStyledImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  size?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
};

export type PageBodyFilter = {
  StyledImage?: InputMaybe<PageBodyStyledImageFilter>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  nav_order?: InputMaybe<NumberFilter>;
  nav_title?: InputMaybe<StringFilter>;
  nav_hidden?: InputMaybe<BooleanFilter>;
  sidebar?: InputMaybe<RichTextFilter>;
  body?: InputMaybe<PageBodyFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConfigBurnStatus: ConfigBurnStatus;
  createConfigBurnStatus: ConfigBurnStatus;
  updateConfigNavigation: ConfigNavigation;
  createConfigNavigation: ConfigNavigation;
  updateConfigSite: ConfigSite;
  createConfigSite: ConfigSite;
  updateConfigPersonnel: ConfigPersonnel;
  createConfigPersonnel: ConfigPersonnel;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConfigBurnStatusArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigBurnStatusMutation;
};


export type MutationCreateConfigBurnStatusArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigBurnStatusMutation;
};


export type MutationUpdateConfigNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigNavigationMutation;
};


export type MutationCreateConfigNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigNavigationMutation;
};


export type MutationUpdateConfigSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigSiteMutation;
};


export type MutationCreateConfigSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigSiteMutation;
};


export type MutationUpdateConfigPersonnelArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigPersonnelMutation;
};


export type MutationCreateConfigPersonnelArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigPersonnelMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  configBurnStatus?: InputMaybe<ConfigBurnStatusMutation>;
  configNavigation?: InputMaybe<ConfigNavigationMutation>;
  configSite?: InputMaybe<ConfigSiteMutation>;
  configPersonnel?: InputMaybe<ConfigPersonnelMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  configBurnStatus?: InputMaybe<ConfigBurnStatusMutation>;
  configNavigation?: InputMaybe<ConfigNavigationMutation>;
  configSite?: InputMaybe<ConfigSiteMutation>;
  configPersonnel?: InputMaybe<ConfigPersonnelMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  page?: InputMaybe<PageMutation>;
};

export type ConfigBurnStatusMutation = {
  fire_status?: InputMaybe<Scalars['String']['input']>;
  burn_season_start?: InputMaybe<Scalars['String']['input']>;
  burn_season_end?: InputMaybe<Scalars['String']['input']>;
  burn_ban_status?: InputMaybe<Scalars['String']['input']>;
  commercial_burn_ban_status?: InputMaybe<Scalars['String']['input']>;
  rec_campfire_status?: InputMaybe<Scalars['String']['input']>;
  state_campfire_status?: InputMaybe<Scalars['String']['input']>;
  np_campfire_status?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigNavigationItemsChildrenMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigNavigationItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  folder?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  children?: InputMaybe<Array<InputMaybe<ConfigNavigationItemsChildrenMutation>>>;
};

export type ConfigNavigationMutation = {
  header_highlight_url?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<ConfigNavigationItemsMutation>>>;
};

export type ConfigSiteAddressMutation = {
  street?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  state?: InputMaybe<Scalars['String']['input']>;
  zip?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  map?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigSiteMutation = {
  site_name?: InputMaybe<Scalars['String']['input']>;
  formal_site_name?: InputMaybe<Scalars['String']['input']>;
  site_desc?: InputMaybe<Scalars['String']['input']>;
  prodUrl?: InputMaybe<Scalars['String']['input']>;
  cloudinarySiteId?: InputMaybe<Scalars['String']['input']>;
  cloudinaryRootUrl?: InputMaybe<Scalars['String']['input']>;
  enable_cloudinary_rewrites?: InputMaybe<Scalars['Boolean']['input']>;
  opengraph_image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<ConfigSiteAddressMutation>;
};

export type ConfigPersonnelPersonnelMutation = {
  first_name?: InputMaybe<Scalars['String']['input']>;
  last_name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  rank?: InputMaybe<Scalars['String']['input']>;
  staff_type?: InputMaybe<Scalars['String']['input']>;
  roles?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  photo?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigPersonnelMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  personnel?: InputMaybe<Array<InputMaybe<ConfigPersonnelPersonnelMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageImage_GalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  image_alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  number_news_stories?: InputMaybe<Scalars['Float']['input']>;
  image_gallery?: InputMaybe<Array<InputMaybe<HomepageImage_GalleryMutation>>>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  nav_order?: InputMaybe<Scalars['Float']['input']>;
  nav_title?: InputMaybe<Scalars['String']['input']>;
  nav_hidden?: InputMaybe<Scalars['Boolean']['input']>;
  sidebar?: InputMaybe<Scalars['JSON']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ConfigBurnStatusPartsFragment = { __typename: 'ConfigBurnStatus', fire_status: string, burn_season_start?: string | null, burn_season_end?: string | null, burn_ban_status: string, commercial_burn_ban_status: string, rec_campfire_status: string, state_campfire_status: string, np_campfire_status: string };

export type ConfigNavigationPartsFragment = { __typename: 'ConfigNavigation', header_highlight_url?: string | null, items?: Array<{ __typename: 'ConfigNavigationItems', label: string, folder?: string | null, url?: string | null, children?: Array<{ __typename: 'ConfigNavigationItemsChildren', label: string, url: string } | null> | null } | null> | null };

export type ConfigSitePartsFragment = { __typename: 'ConfigSite', site_name: string, formal_site_name?: string | null, site_desc?: string | null, prodUrl?: string | null, cloudinarySiteId?: string | null, cloudinaryRootUrl?: string | null, enable_cloudinary_rewrites?: boolean | null, opengraph_image?: string | null, address?: { __typename: 'ConfigSiteAddress', street?: string | null, city?: string | null, state?: string | null, zip?: string | null, phone?: string | null, map?: string | null } | null };

export type ConfigPersonnelPartsFragment = { __typename: 'ConfigPersonnel', title: string, body?: any | null, personnel?: Array<{ __typename: 'ConfigPersonnelPersonnel', first_name: string, last_name: string, title?: string | null, rank?: string | null, staff_type: string, roles?: Array<string | null> | null, photo?: string | null } | null> | null };

export type HomepagePartsFragment = { __typename: 'Homepage', title: string, number_news_stories?: number | null, image_gallery?: Array<{ __typename: 'HomepageImage_gallery', image: string, image_alt: string } | null> | null };

export type PagePartsFragment = { __typename: 'Page', title: string, nav_order?: number | null, nav_title?: string | null, nav_hidden?: boolean | null, sidebar?: any | null, body?: any | null };

export type ConfigBurnStatusQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigBurnStatusQuery = { __typename?: 'Query', configBurnStatus: { __typename: 'ConfigBurnStatus', id: string, fire_status: string, burn_season_start?: string | null, burn_season_end?: string | null, burn_ban_status: string, commercial_burn_ban_status: string, rec_campfire_status: string, state_campfire_status: string, np_campfire_status: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ConfigBurnStatusConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigBurnStatusFilter>;
}>;


export type ConfigBurnStatusConnectionQuery = { __typename?: 'Query', configBurnStatusConnection: { __typename?: 'ConfigBurnStatusConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigBurnStatusConnectionEdges', cursor: string, node?: { __typename: 'ConfigBurnStatus', id: string, fire_status: string, burn_season_start?: string | null, burn_season_end?: string | null, burn_ban_status: string, commercial_burn_ban_status: string, rec_campfire_status: string, state_campfire_status: string, np_campfire_status: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ConfigNavigationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigNavigationQuery = { __typename?: 'Query', configNavigation: { __typename: 'ConfigNavigation', id: string, header_highlight_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ConfigNavigationItems', label: string, folder?: string | null, url?: string | null, children?: Array<{ __typename: 'ConfigNavigationItemsChildren', label: string, url: string } | null> | null } | null> | null } };

export type ConfigNavigationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigNavigationFilter>;
}>;


export type ConfigNavigationConnectionQuery = { __typename?: 'Query', configNavigationConnection: { __typename?: 'ConfigNavigationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigNavigationConnectionEdges', cursor: string, node?: { __typename: 'ConfigNavigation', id: string, header_highlight_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ConfigNavigationItems', label: string, folder?: string | null, url?: string | null, children?: Array<{ __typename: 'ConfigNavigationItemsChildren', label: string, url: string } | null> | null } | null> | null } | null } | null> | null } };

export type ConfigSiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigSiteQuery = { __typename?: 'Query', configSite: { __typename: 'ConfigSite', id: string, site_name: string, formal_site_name?: string | null, site_desc?: string | null, prodUrl?: string | null, cloudinarySiteId?: string | null, cloudinaryRootUrl?: string | null, enable_cloudinary_rewrites?: boolean | null, opengraph_image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address?: { __typename: 'ConfigSiteAddress', street?: string | null, city?: string | null, state?: string | null, zip?: string | null, phone?: string | null, map?: string | null } | null } };

export type ConfigSiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigSiteFilter>;
}>;


export type ConfigSiteConnectionQuery = { __typename?: 'Query', configSiteConnection: { __typename?: 'ConfigSiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigSiteConnectionEdges', cursor: string, node?: { __typename: 'ConfigSite', id: string, site_name: string, formal_site_name?: string | null, site_desc?: string | null, prodUrl?: string | null, cloudinarySiteId?: string | null, cloudinaryRootUrl?: string | null, enable_cloudinary_rewrites?: boolean | null, opengraph_image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address?: { __typename: 'ConfigSiteAddress', street?: string | null, city?: string | null, state?: string | null, zip?: string | null, phone?: string | null, map?: string | null } | null } | null } | null> | null } };

export type ConfigPersonnelQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigPersonnelQuery = { __typename?: 'Query', configPersonnel: { __typename: 'ConfigPersonnel', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personnel?: Array<{ __typename: 'ConfigPersonnelPersonnel', first_name: string, last_name: string, title?: string | null, rank?: string | null, staff_type: string, roles?: Array<string | null> | null, photo?: string | null } | null> | null } };

export type ConfigPersonnelConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigPersonnelFilter>;
}>;


export type ConfigPersonnelConnectionQuery = { __typename?: 'Query', configPersonnelConnection: { __typename?: 'ConfigPersonnelConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigPersonnelConnectionEdges', cursor: string, node?: { __typename: 'ConfigPersonnel', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personnel?: Array<{ __typename: 'ConfigPersonnelPersonnel', first_name: string, last_name: string, title?: string | null, rank?: string | null, staff_type: string, roles?: Array<string | null> | null, photo?: string | null } | null> | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, title: string, number_news_stories?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image_gallery?: Array<{ __typename: 'HomepageImage_gallery', image: string, image_alt: string } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, title: string, number_news_stories?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image_gallery?: Array<{ __typename: 'HomepageImage_gallery', image: string, image_alt: string } | null> | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, nav_order?: number | null, nav_title?: string | null, nav_hidden?: boolean | null, sidebar?: any | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, nav_order?: number | null, nav_title?: string | null, nav_hidden?: boolean | null, sidebar?: any | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ConfigBurnStatusPartsFragmentDoc = gql`
    fragment ConfigBurnStatusParts on ConfigBurnStatus {
  __typename
  fire_status
  burn_season_start
  burn_season_end
  burn_ban_status
  commercial_burn_ban_status
  rec_campfire_status
  state_campfire_status
  np_campfire_status
}
    `;
export const ConfigNavigationPartsFragmentDoc = gql`
    fragment ConfigNavigationParts on ConfigNavigation {
  __typename
  header_highlight_url
  items {
    __typename
    label
    folder
    url
    children {
      __typename
      label
      url
    }
  }
}
    `;
export const ConfigSitePartsFragmentDoc = gql`
    fragment ConfigSiteParts on ConfigSite {
  __typename
  site_name
  formal_site_name
  site_desc
  prodUrl
  cloudinarySiteId
  cloudinaryRootUrl
  enable_cloudinary_rewrites
  opengraph_image
  address {
    __typename
    street
    city
    state
    zip
    phone
    map
  }
}
    `;
export const ConfigPersonnelPartsFragmentDoc = gql`
    fragment ConfigPersonnelParts on ConfigPersonnel {
  __typename
  title
  personnel {
    __typename
    first_name
    last_name
    title
    rank
    staff_type
    roles
    photo
  }
  body
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  title
  number_news_stories
  image_gallery {
    __typename
    image
    image_alt
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  nav_order
  nav_title
  nav_hidden
  sidebar
  body
}
    `;
export const ConfigBurnStatusDocument = gql`
    query configBurnStatus($relativePath: String!) {
  configBurnStatus(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigBurnStatusParts
  }
}
    ${ConfigBurnStatusPartsFragmentDoc}`;
export const ConfigBurnStatusConnectionDocument = gql`
    query configBurnStatusConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigBurnStatusFilter) {
  configBurnStatusConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigBurnStatusParts
      }
    }
  }
}
    ${ConfigBurnStatusPartsFragmentDoc}`;
export const ConfigNavigationDocument = gql`
    query configNavigation($relativePath: String!) {
  configNavigation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigNavigationParts
  }
}
    ${ConfigNavigationPartsFragmentDoc}`;
export const ConfigNavigationConnectionDocument = gql`
    query configNavigationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigNavigationFilter) {
  configNavigationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigNavigationParts
      }
    }
  }
}
    ${ConfigNavigationPartsFragmentDoc}`;
export const ConfigSiteDocument = gql`
    query configSite($relativePath: String!) {
  configSite(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigSiteParts
  }
}
    ${ConfigSitePartsFragmentDoc}`;
export const ConfigSiteConnectionDocument = gql`
    query configSiteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigSiteFilter) {
  configSiteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigSiteParts
      }
    }
  }
}
    ${ConfigSitePartsFragmentDoc}`;
export const ConfigPersonnelDocument = gql`
    query configPersonnel($relativePath: String!) {
  configPersonnel(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigPersonnelParts
  }
}
    ${ConfigPersonnelPartsFragmentDoc}`;
export const ConfigPersonnelConnectionDocument = gql`
    query configPersonnelConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigPersonnelFilter) {
  configPersonnelConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigPersonnelParts
      }
    }
  }
}
    ${ConfigPersonnelPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      configBurnStatus(variables: ConfigBurnStatusQueryVariables, options?: C): Promise<{data: ConfigBurnStatusQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigBurnStatusQueryVariables, query: string}> {
        return requester<{data: ConfigBurnStatusQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigBurnStatusQueryVariables, query: string}, ConfigBurnStatusQueryVariables>(ConfigBurnStatusDocument, variables, options);
      },
    configBurnStatusConnection(variables?: ConfigBurnStatusConnectionQueryVariables, options?: C): Promise<{data: ConfigBurnStatusConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigBurnStatusConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigBurnStatusConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigBurnStatusConnectionQueryVariables, query: string}, ConfigBurnStatusConnectionQueryVariables>(ConfigBurnStatusConnectionDocument, variables, options);
      },
    configNavigation(variables: ConfigNavigationQueryVariables, options?: C): Promise<{data: ConfigNavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigNavigationQueryVariables, query: string}> {
        return requester<{data: ConfigNavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigNavigationQueryVariables, query: string}, ConfigNavigationQueryVariables>(ConfigNavigationDocument, variables, options);
      },
    configNavigationConnection(variables?: ConfigNavigationConnectionQueryVariables, options?: C): Promise<{data: ConfigNavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigNavigationConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigNavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigNavigationConnectionQueryVariables, query: string}, ConfigNavigationConnectionQueryVariables>(ConfigNavigationConnectionDocument, variables, options);
      },
    configSite(variables: ConfigSiteQueryVariables, options?: C): Promise<{data: ConfigSiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigSiteQueryVariables, query: string}> {
        return requester<{data: ConfigSiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigSiteQueryVariables, query: string}, ConfigSiteQueryVariables>(ConfigSiteDocument, variables, options);
      },
    configSiteConnection(variables?: ConfigSiteConnectionQueryVariables, options?: C): Promise<{data: ConfigSiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigSiteConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigSiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigSiteConnectionQueryVariables, query: string}, ConfigSiteConnectionQueryVariables>(ConfigSiteConnectionDocument, variables, options);
      },
    configPersonnel(variables: ConfigPersonnelQueryVariables, options?: C): Promise<{data: ConfigPersonnelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigPersonnelQueryVariables, query: string}> {
        return requester<{data: ConfigPersonnelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigPersonnelQueryVariables, query: string}, ConfigPersonnelQueryVariables>(ConfigPersonnelDocument, variables, options);
      },
    configPersonnelConnection(variables?: ConfigPersonnelConnectionQueryVariables, options?: C): Promise<{data: ConfigPersonnelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigPersonnelConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigPersonnelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigPersonnelConnectionQueryVariables, query: string}, ConfigPersonnelConnectionQueryVariables>(ConfigPersonnelConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:7071/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  