ci:
  collect:
    # collect options here
    staticDistDir: ./public
    isSinglePageApplication: false
    settings:
      chromeFlags: "--disable-gpu --no-sandbox"
  assert:
    # assert options here
    preset: 'lighthouse:recommended'
  upload:
    # upload options here

  server:
    # server options here

  wizard:
    # wizard options here
