[build]
  base    = '.'
# NOTE: cannot use with admin/ in its own folder; this overwrites the admin build commands set in the GUI
#  publish = "public"
#  command = "npm run build"
[context.production]
  environment = { ELEVENTY_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = [
    './public/services/*',
    './public/reports/*'
  ]

# disable for now because:
#  - it causes admin sub-domain to not deploy
#  - it is REALLY expensive to run and we'll run out of build minutes
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   [plugins.inputs.thresholds]
#     performance = 0.9
# #    accessibility = 0.9
#     best-practices = 0.9
#     seo = 0.9
#  #   pwa = 0.9
#   [plugins.inputs]
#     output_path = "reports/lighthouse.html"
