[build]
  base    = '.'
  publish = "public"
  command = "npm run build"
[context.production]
  environment = { ELEVENTY_ENV = "production" }

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './public/services/*'
  ]
