[build]
  base    = '.'
# NOTE: cannot use with admin/ in its own folder; this overwrites the admin build commands set in the GUI
#  publish = "public"
#  command = "npm run build"
[context.production]
  environment = { ELEVENTY_ENV = "production" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
#    Content-Security-Policy-Report-Only = "default-src 'self' *.cloudinary.com *.clarity.ms *.googletagmanager.com *.google.com;"
#    Content-Security-Policy = "default-src 'self' *.cloudinary.com *.clarity.ms *.googletagmanager.com *.google.com;"

# [[plugins]]
#  package = "netlify-plugin-csp-generator"
#  [plugins.inputs]
#   buildDir = "{public,admin}"
#    buildDir = "public"
#  [plugins.inputs.policies]
#    defaultSrc = "'self' *.google.com"
#    scriptSrc  = "'self' *.googletagmanager.com *.clarity.ms"
#    imgSrc     = "'self' *.cloudinary.com"
#   reportOnly = true
#    reportURI = "/report-csp-violations-to-this-uri"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = [
    './public/reports/**'
  ]


[[redirects]]
  from = "/governance"
  to = "/about/governance"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/about/who-we-are"
  status = 301
  force = true



# disable for now because:
#  - it causes admin sub-domain to not deploy
#  - it is REALLY expensive to run and we'll run out of build minutes
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   [plugins.inputs.thresholds]
#     performance = 0.9
# #    accessibility = 0.9
#     best-practices = 0.9
#     seo = 0.9
#  #   pwa = 0.9
#   [plugins.inputs]
#     output_path = "reports/lighthouse.html"
