[build]
  base    = '.'
  publish = "public"
  command = "npm run build"
[context.production]
  environment = { ELEVENTY_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = [
    './public/services/*'
  ]


[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

