backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
site_url: "https://sjifire.org/"
show_preview_links: false
publish_mode: editorial_workflow
collections:

  - name: "news_posts"
    label: "Post: News"
    label_singular: "News Post"
    folder: "src/posts/"
    filter: {field: "post_type", value: "news"}
    slug: "{{fields.date}}-{{slug}}"
    extension: "md"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    summary: "{{fields.date | date('YYYY-MM-DD')}} • {{fields.title}}"
    description: "News posts on the site."
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
        required: true
      - label: Layout
        name: layout
        widget: hidden
        default: post.njk
        required: false
      - label: Post Type
        name: post_type
        widget: hidden
        default: "news"
        required: false
      - label: Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        picker_utc: true
        default: ''
        hint: Publication date
        required: true
      - label: Teaser (Lede)
        name: lede
        widget: text
        hint: Short snipped of text used in article teasers
        required: true
      - label: Body Content
        name: body
        widget: markdown
        minimal: false
        buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
        editor_components: [image]
        modes: [rich_text]
        required: false
        hint: "Add a chunk of text (rich text editor)"
    sortable_fields:
      - date
      - commit_date
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Post Type
        field: post_type

  - name: "advisory_posts"
    label: "Post: Advisory"
    label_singular: "Advisory Post"
    folder: "src/posts/"
    filter: {field: "post_type", value: "advisory"}
    slug: "{{fields.date}}-{{slug}}"
    extension: "md"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    summary: "{{fields.date | date('YYYY-MM-DD')}} • {{fields.title}}"
    description: "Advisory posts on the site."
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
        required: true
      - label: Layout
        name: layout
        widget: hidden
        default: post.njk
        required: false
      - label: Post Type
        name: post_type
        widget: hidden
        default: "advisory"
        required: false
      - label: Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        picker_utc: true
        default: ''
        hint: Publication date
        required: true
      - label: Teaser (Lede)
        name: lede
        widget: text
        hint: Short snipped of text used in article teasers
        required: true
      - label: Body Content
        name: body
        widget: markdown
        minimal: false
        buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
        editor_components: [image]
        modes: [rich_text]
        required: false
        hint: "Add a chunk of text (rich text editor)"
    sortable_fields:
      - date
      - commit_date
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Post Type
        field: post_type


  - name: pages
    label: "Pages"
    description: "Edit pages across the site."
    files:
      - label: "Homepage"
        name: "homepage"
        delete: false
        editor:
          preview: false
        file: "src/_data/homepage.json"
        fields:
          - label: Preamble
            name: preamble
            widget: text
            hint: >-
              Text that appears under the main heading.
      - label: "About"
        name: "about"
        delete: false
        editor:
          preview: false
        file: "src/_data/about.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: []
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
          - sections:
            name: "sections"
            widget: "list"
            collapsed: true
            add_to_top: true
            hint: "Add discrete sections of content to this page. The sections you can choose from: 'text', 'image', 'youtube'."
            required: true
            types:
              - label: "Text Section"
                name: "text"
                widget: "object"
                fields:
                  - label: Rich Text
                    name: copy
                    widget: markdown
                    minimal: false
                    buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
                    editor_components: []
                    modes: [rich_text]
                    required: false
                    hint: "Add a chunk of text (rich text editor)"
              - label: "Image"
                name: "image"
                widget: "object"
                hint: "Add an image to the post, complete with 'alt' tag and, optionally, a caption"
                fields:
                  - label: Image Upload
                    name: source
                    widget: image
                    allow_multiple: false
                    choose_url: false
                    media_folder: /src/assets/
                    public_folder: ''
                  - label: Width
                    name: width
                    widget: number
                    hint: "What is the width of this image?"
                  - label: Height
                    name: height
                    widget: number
                    hint: "What is the height of this image"
                  - label: Alternative Text
                    name: alt
                    widget: string
                    hint: "Provide alternative ('alt') text for this image"
                  - label: Image Caption
                    name: caption
                    widget: string
                    hint: "Add a caption for the image (optional)"
              - label: "YouTube Video"
                name: "youtube"
                widget: "object"
                fields:
                  - label: YouTube Video Link
                    name: source
                    widget: string
                    hint: "Add a YouTube video player by copy-pasting the 'Share' link"
                  - label: Video Caption
                    name: caption
                    widget: string
                    hint: "Add a caption for the video (optional)"
      - label: "Governance"
        name: "governance"
        delete: false
        editor:
          preview: false
        file: "src/_data/governance.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Services"
        name: "services"
        delete: false
        editor:
          preview: false
        file: "src/_data/services.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Contact"
        name: "contact"
        delete: false
        editor:
          preview: false
        file: "src/_data/contact.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Thank You"
        name: "thank_you"
        delete: false
        editor:
          preview: false
        file: "src/_data/thank_you.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "404 Error - Page Not Found"
        name: "error_404"
        delete: false
        editor:
          preview: false
        file: "src/_data/error_404.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
