backend:
  name: git-gateway
  branch: main
media_folder: "src/images/"
public_folder: "/images/"
site_url: "https://sjifr.org/"
show_preview_links: false
collections:

  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "blog/"
    path: "{{year}}/{{slug}}"
    slug: "{{fields.date | date('MM-DD')}}-{{slug}}"
    extension: "md"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    summary: "{{fields.date | date('YYYY-MM-DD')}} • {{fields.title}}"
    description: "Blog posts / news on the site."
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
        required: true
      - label: Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        picker_utc: true
        default: ''
        hint: Publication date
        required: true
      - label: Published?
        name: published
        widget: boolean
        hint: Published = true (blue, switch toggled right). Draft = false (gray, switch toggled left).
        default: false
      - label: Category
        name: tags
        widget: select
        options: 
          - { label: "Announcement", value: "announcement" }
          - { label: "Advisory", value: "advisory" }
          - { label: "News", value: "news" }
        hint: Category this article should be filed under.
        required: true
      - label: Teaser (Lede)
        name: lede
        widget: text
        hint: Short snipped of text used in article teasers
        required: true
      - label: Body Content
        name: body
        widget: markdown
        minimal: false
        buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
        editor_components: []
        modes: [rich_text]
        required: false
        hint: "Add a chunk of text (rich text editor)"
    sortable_fields:
      - date
      - commit_date
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Category
        field: category
      - label: Published?
        field: published


  # - name: "site_info"
  #   label: "Site Settings"
  #   description: "Set global variables here."
  #   files:
  #     - label: "Meta"
  #       name: "meta"
  #       delete: false
  #       editor:
  #         preview: false
  #       file: "src/_data/site.json"
  #       fields:
  #         - label: Site Title
  #           name: title
  #           widget: string
  #           hint: 'Text that appears in search results, when shared on social media, etc.'
  #         - label: Site Description
  #           name: description
  #           widget: text
  #           hint: >-
  #             Text that appears below title in search results and sometimes on social
  #             media. Google truncates around 160 characters.
  #           pattern:
  #             - '.{1,160}'
  #             - Should be 160 characters or less.
  #         - label: Site Url
  #           name: url
  #           widget: string
  #         - label: Social Share Image
  #           name: og_img
  #           widget: image
  #           allow_multiple: false
  #           media_folder: /src/images/social/

