backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/"
public_folder: "/assets/"
site_url: "https://sjifr.org/"
show_preview_links: false
collections:

  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "src/posts/"
    path: '{{fields.post_type}}/'
    slug: "{{fields.date}}-{{slug}}"
    extension: "md"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    summary: "{{fields.date | date('YYYY-MM-DD')}} • {{fields.title}}"
    description: "Blog posts / news on the site."
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
        required: true
      - label: Layout
        name: layout
        widget: hidden
        default: post.njk
        required: false
      - label: Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        picker_utc: true
        default: ''
        hint: Publication date
        required: true
      - label: Post Type
        name: post_type
        widget: select
        options: 
          - { label: "Advisory", value: "advisory" }
          - { label: "News", value: "news" }
        hint: The type of post will effect where it appears on the homepage.
        required: true
      - label: Teaser (Lede)
        name: lede
        widget: text
        hint: Short snipped of text used in article teasers
        required: true
      - label: Body Content
        name: body
        widget: markdown
        minimal: false
        buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
        editor_components: [image]
        modes: [rich_text]
        required: false
        hint: "Add a chunk of text (rich text editor)"
    sortable_fields:
      - date
      - commit_date
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Post Type
        field: post_type


  - name: pages
    label: "Pages"
    description: "Edit pages across the site."
    files:
      - label: "Homepage"
        name: "homepage"
        delete: false
        editor:
          preview: false
        file: "src/_data/homepage.json"
        fields:
          - label: Preamble
            name: preamble
            widget: text
            hint: >-
              Text that appears under the main heading.
      - label: "About"
        name: "about"
        delete: false
        editor:
          preview: false
        file: "src/_data/about.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Governance"
        name: "governance"
        delete: false
        editor:
          preview: false
        file: "src/_data/governance.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Service"
        name: "service"
        delete: false
        editor:
          preview: false
        file: "src/_data/service.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Contact"
        name: "contact"
        delete: false
        editor:
          preview: false
        file: "src/_data/contact.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "Thank You"
        name: "thank_you"
        delete: false
        editor:
          preview: false
        file: "src/_data/thank_you.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"
      - label: "404 Error - Page Not Found"
        name: "error_404"
        delete: false
        editor:
          preview: false
        file: "src/_data/error_404.json"
        fields:
          - label: Preamble
            name: preamble
            widget: markdown
            minimal: false
            buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: [image]
            modes: [rich_text]
            required: false
            hint: "Add a chunk of text (rich text editor)"