name: Lighthouse CI

on: [workflow_dispatch]
# on: [push, workflow_dispatch]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci healthcheck --config='.github/lighthouserc.json' --fatal
          lhci autorun --config='.github/lighthouserc.json'
        # env:
        #   LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-results
          path: '.lighthouseci'

