name: Lighthouse CI
on: [push, pull_request, workflow_dispatch]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: 'npm'
      - run: npm install && npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: lhci autorun --config=.github/lighthouserc.yml
