name: Trigger Netlify Build
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # At minutes 45 past 08h and 20h
    - cron: "45 8,20 * * *"
jobs:
  build:
    name: Trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_URL }}
