name: Schedule Netlify Build
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # 0815 UTC ~ 0115 Pacific
    - cron: "*/10 * * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_URL_WEB }}
